### ISSUE TITLE
BaseDispatchComponent.setValue requires existing XML file with root node

### ISSUE THREAD

**Issue by SoccerFive18** [LK-Test-Solutions/OpenTDK#13]

**Comment by hwalter67** [comment]
Method org.opentdk.api.dispatcher.BaseDispatcherComponent#check extended with a rootNode argument, so that the newly created instance of org.opentdk.api.io.XMLEditor will create the XML header and rootTag in case the file is empty. This requires to call the method BaseDispatcher.setDataContainer also with the rootNode argument like shown in the following sample:

**_BaseDispatcher.setDataContainer(ERuntimeProperties.class, "./conf/AppSettings.xml", ERuntimeProperties.HOMEDIR.getRootNode());_**

You still need to use the getRootNode method from one of the declared fields within the dispatcher class. Here the dispatcher class is ERuntimeProperties and the used field is HOMEDIR. Also any other field declared within ERuntimeProperties can be used to retrieve the rootNode, because every XML file only has a single rootNode.
